src/.gitignore
src/package.json
src/test/jws.js

1. add test coverage - jws negative cases 2. bump package version

---

src/lib/jws/jwsSigner.js
src/package.json

1. fix leftover body manipulation from previous change 2. bump package version

---

src/lib/mojaloop-requests/wso2auth.js
src/package.json

Logger only supports logger.log

fix logging call errors

---

package-lock.json
src/package-lock.json
src/package.json

- Remove unused package-lock.json
- Bump version to v8.6.1

Remove unnecessary package-lock.json

---

src/lib/mojaloop-requests/mojaloopRequests.js

* Add transactionRequests endpoints to mojaloopRequests.js

feat (transactionRequests)

---

src/lib/mojaloop-requests/mojaloopRequests.js

If wso2Auth is not required the headers can still be built now

Fix conditional wso2

---

.circleci/config.yml
src/package-lock.json
src/package.json

- Updated CircleCI config to use Node 12.15.0 LTS 
- Updated dependencies 
- Bumped version to v9.1.0

#1228 - Upgrade to Node 12.16.0 LTS

---

src/lib/mojaloop-requests/mojaloopRequests.js

Customize internal HTTP methods to be able to process non-Mojaloop HTTP response.

MP-1140: Customize internal HTTP methods

---

src/lib/errors/index.js
src/package.json

Changes:
- Added new error type for 405 errors
- Updated version 10.2.4
Fix for bug: https://github.com/mojaloop/project/issues/1331

Added new 405 error type

---

src/package.json

bump version to prepare the release for publishing changes related to PISP - changes are already merged with master
* GET/POST thirdparty requests
* POST authorizations request

bump version

---

src/index.d.ts
src/package.json

Following https://github.com/mojaloop/pisp/tree/master/docs/linking#161-requesting-a-challenge
Change type of challenge.payload, challenge.signature, payload from ArrayBuffer to string
@lewisdaly  Can't seem to assign you as a reviewer but please take a look

Update definition of PutConsentsRequest type

---

src/index.d.ts
src/lib/requests/thirdpartyRequests.js
src/test/unit/data/postConsentRequestsRequest.json
src/test/unit/data/postConsentsRequest.json
src/test/unit/data/putConsentRequestsRequest.json
src/test/unit/lib/requests/thirdpartyRequests.test.js

Added POST /consents and POST/PUT /consentRequests call and bumped version

---

src/index.d.ts
src/lib/requests/baseRequests.js
src/package.json

Following https://github.com/mojaloop/pisp/tree/master/docs/linking#161-requesting-a-challenge
@eoln @kleyow  please review (mainly the last commit)

Update TCredential Type + Enforce jwsSigningKey as optional for BaseRequest config

---

src/index.d.ts

@bushjames quick fix that was missed in a previous PR.

Fixed type name.

---

src/lib/jws/jwsSigner.js
src/package.json

These technically aren't in the ML api spec...but we're going to need them for PISP work. 
Lmk if you want this handled differently for any reason...James.

Added thirdparty requests to jws signing regex.

---

src/package.json

Bump Version to 11.0.0

---

src/index.d.ts
src/package.json

Change TCredential Status enum: `ACTIVE` -> `VERIFIED` 
To reflect linking diagram https://github.com/mojaloop/pisp/tree/master/docs/linking#162-finalizing-the-credential
With @lewisdaly

Update TCredential Type

---

src/index.d.ts
src/package.json

https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/1648

Update Type Definitions

---

src/index.d.ts
src/package.json

extent index.d.ts typing files by adding declaration for WSO2Auth class

feat: TS typings for WSO2Auth class

---

CODEOWNERS
README.md
src/index.d.ts
src/package.json

- clean up typescript typings
- added typings for Logger module
- update jest and @types/node dev-deps
- volunteer to become code owner

feat: sdk logger typescript typings

---

CODEOWNERS
README.md
src/index.d.ts
src/package.json

there was a need to refactor invalid typings

refactor: sdk logger ts typings

---

README.md
src/index.d.ts
src/package.json

TypeScript typings for `request` module

feat: TS typings for request module

---

src/index.d.ts
src/package.json

extending TS typings for breaking change in `config` argument for BaseRequests constructor

feat: extend TS typings for v12 breaking change

---

.circleci/config.yml
src/lib/WSO2Auth/index.js
src/lib/request.js
src/lib/requests/baseRequests.js
src/package-lock.json
src/package.json
src/test/unit/WSO2Auth.test.js
src/test/unit/lib/requests/baseRequests.test.js
src/test/unit/log.test.js

- Updated test to reflect new dependency API
- Added package-lock.json to prevent dependencies shifting beneath us in future
- WSO2 auth error emission on token request failure
- Optional token refresh and request retry on 401 response when WSO2 auth configured

Features and bugfixes related to WSO2 auth

---

src/lib/request.js
src/package-lock.json
src/package.json
src/test/unit/lib/requests/request-errors.test.js

Tag on the original request details (as an object) to errors thrown from the underlying request module.

add original request object to errors thrown from request module

---

src/index.d.ts
src/lib/requests/thirdpartyRequests.js
src/test/unit/data/patchThirdpartyRequestTransaction.json
src/test/unit/lib/requests/thirdpartyRequests.test.js

expose PATCH /thirdpartyRequests/transaction/{ID} endpoint

feat: patchThirdpartyRequestsTransaction

---

src/lib/requests/mojaloopRequests.js
src/package-lock.json
src/package.json

allow optional setting of destination fspid for GET requests in mojaloop requests module

feature: allow optional setting of destination fspid for GET requests

---

src/package-lock.json
src/package.json

chore: bump version to 16.0.0

---

package-lock.json
package.json

chore: updated dependencies for v17 release

---

.circleci/config.yml
README.md
package-lock.json
package.json

docs(mojaloop/#3454): update readme
- updated readme
- updated dependencies

docs(mojaloop/#3454): update readme

---

package-lock.json
package.json
src/lib/WSO2Auth/index.js
src/lib/ilp/index.js
src/lib/jws/jwsSigner.js
src/lib/jws/jwsValidator.js
src/lib/logger/index.js
src/lib/requests/baseRequests.js
test/unit/log.test.js

feat(mojaloop/#3750): add isLevelEnabled functions - https://github.com/mojaloop/project/issues/3750

feat(mojaloop/#3750): add isLevelEnabled functions

---

package-lock.json
package.json
src/index.d.ts
src/index.js
src/lib/constants.js
src/lib/errors/index.js
src/lib/ilp/index.js
src/lib/requests/baseRequests.js
src/lib/requests/mojaloopRequests.js

feat(mojaloop/#3618): add support for POST /fxQuotes and /fxTransfers - https://github.com/mojaloop/project/issues/3618

feat(mojaloop/#3618): add support for POST /fxQuotes and /fxTransfers

---

audit-ci.jsonc
package-lock.json
package.json
src/index.d.ts
src/index.js
src/lib/constants.js
src/lib/dto.js
src/lib/errors/index.js
src/lib/ilp/index.js
src/lib/jws/jwsSigner.js
src/lib/requests/baseRequests.js
src/lib/requests/mojaloopRequests.js
test/fixtures.js
test/unit/ilp.test.js

feat: fx-impl

---

jest.config.js

This needs to be increased to moja defaults of 90% asap. Reducing as a volume of work is required here to get to normal status quo.

chore: reducing unit test coverage threshold temporarily.

---

package-lock.json
package.json
src/lib/httpRequester/index.js
src/lib/ilp/IlpBase.js
src/lib/ilp/IlpV4.js
test/unit/lib/ilp/IlpV4.test.js
test/unit/lib/requests/thirdpartyRequests.test.js

-update dependencies
-replace source code headers to Mojaloop Foundation

chore: maintenance updates

---

package-lock.json
package.json
src/lib/httpRequester/AxiosHttpRequester.js

Remove unneeded error response info from logs:

chore: fixed error response logs
